name: leap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  flutter_map: ^7.0.2
  location: ^7.0.1
  latlong2: ^0.9.1
  flutter_svg: ^1.0.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icons"
  ios: "AppIcon"
  image_path: "assets/icon/terno.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/terno.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/terno.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/terno.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/bayside.jpeg
    - assets/icon/didi.png
    - assets/icon/eightfold.png
    - assets/icon/infosys.jpg
    - assets/icon/merce.jpg
    - assets/icon/coinjar.png
    - assets/icon/redbull.png
    - assets/icon/terno.png

    - assets/icon/instagram.svg
    - assets/icon/twitter.svg
    - assets/icon/tiktok.svg
    - assets/icon/linkedin.svg

    - assets/image/bg.jpeg

